//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ChannelId { get; set; }
        public string Name { get; set; }
        public bool OpenForSender { get; set; }
        public bool OpenForReciever { get; set; }
        public int RecieverId { get; set; }
        public int SenderId { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
